# Generated by Django 5.1.7 on 2025-03-11 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organizacion',
            fields=[
                ('nombre', models.CharField(max_length=50)),
                ('cuit', models.CharField(max_length=11, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('fechaVencimiento', models.DateField(verbose_name='fecha de vencimiento')),
                ('periodo', models.IntegerField(choices=[(1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')])),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pagado', models.BooleanField(default=False)),
                ('organizacion', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pagos.organizacion')),
            ],
        ),
    ]
